CREATE TABLE
users(user_id INT PRIMARY KEY,
name VARCHAR(255));

CREATE TABLE
POSTS(post_id INT PRIMARY KEY,
message VARCHAR(255),
user_id INT);

CREATE TABLE
HIBERNATE_SEQUENCES (
SEQUENCE_NAME VARCHAR(255),
NEXT_VAL BIGINT(19)
)
